src/Entity/Pin.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\PinRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("title", message="Ce titre a déjà été utilisé, veuillez réessayer un autre!")
 * @Vich\Uploadable
 */
class Pin
{
    use Timestampable;

    public const NBRE_ELE_PAR_PAGE = 6;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Length(min = 5, minMessage = "Le titre doit avoir au minimun {{ limit }} caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Length(min = 10, minMessage = "La description doit avoir au minimun {{ limit }} caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\File(maxSize = "8M", maxSizeMessage="L'image est trop grande la taille est de ({{ size }} {{ suffix }}). La taille maximale doit être de {{ limit }} {{ suffix }}.")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cet e-mail")
 */
class User implements UserInterface
{
    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Length(min = 3, minMessage = "Le prénom doit avoir au minimun {{ limit }} caractères")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Length(min = 3, minMessage = "Le nom doit avoir au minimun {{ limit }} caractères")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Ce champ est requis")
     * @Assert\Email(message = "Le mail '{{ value }}' n'est pas valide.")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getGravatarUrl(?int $size = 100)
    {
       // return "https://www.gravatar.com/avatar/" . md5( strtolower( trim($this->getEmail()) ) ) . "&s=" . $size;

       return sprintf('https://www.gravatar.com/avatar/%s?s=%d', md5( strtolower( trim($this->getEmail()) ) ), $size);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image (JPG ou PNG)',
                'required' => false,
                'allow_delete' => true,
                'delete_label' => 'Supprimer?',
                'download_uri' => false,
                'imagine_pattern' => 'image_taille_petite',
            ])
            ->add('title', TextType::class, ['label' => 'Titre'])
            ->add('description', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class PinsController extends AbstractController
{
    /**
     * @Route("/", name="app_home", methods={"GET"})
     */
    public function index(PinRepository $pinRepo, Request $request, PaginatorInterface $paginator): Response
    {
        $data = $pinRepo->findBy([], ['createdAt' => 'DESC']);

        $pins = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1), /*page number*/
            Pin::NBRE_ELE_PAR_PAGE /*limit per page*/
        );

        return $this->render('pins/index.html.twig', [
            'pins' => $pins,
        ]);
    }

    /**
     * @Route("/pins/create", name="app_pins_create", methods={"GET", "POST"})
     * @IsGranted("PIN_CREATE")
     */
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $pin = new Pin;
        $form = $this->createForm(PinType::class, $pin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $pin = $pin->SetUser($this->getUser());
            $em->persist($pin);
            $em->flush();
            $this->addFlash('success', 'Votre création a été publiée avec succès!');
            return $this->redirectToRoute('app_home');
            
        }
        
        return $this->render('pins/create.html.twig', [
            'form' => $form->createView(),
            'current_menu' => 'new'
        ]);
    }

    /**
     * @Route("/pins/{slug}", name="app_pins_show", methods={"GET"})
     */
    public function show(Pin $pin): Response
    {
        return $this->render('pins/show.html.twig', [
            'pin' => $pin
        ]);
    }

    /**
     * @Route("/pins/{slug}/edit", name="app_pins_edit", methods={"GET", "PUT"})
     * @security("is_granted('PIN_MANAGE', pin)")
     */
    public function edit(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(PinType::class, $pin, [
            'method' => 'PUT'
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
    
            $em->flush();
            $this->addFlash('success', 'Votre création a été modifiée avec succès!');
            return $this->redirectToRoute('app_home');
        }
        
        return $this->render('pins/edit.html.twig', [
            'form' => $form->createView(),
            'pin' => $pin,
        ]);
    }

    /**
     * @Route("/pins/{slug}", name="app_pins_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('PIN_MANAGE', $pin);
        
        if ($this->isCsrfTokenValid('pin_deletion_' . $pin->getId(), $request->request->get('csrf_token'))) {
            $em->remove($pin);
            $em->flush();
        }
        $this->addFlash('success', 'Votre création a été supprimée avec succès!');
        return $this->redirectToRoute('app_home');   
    }
}

templates/pins/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form)}}
    <div class="mt-2 d-grid gap-2">
        <input class="btn btn-primary" type="submit" value="{{ submitButtonText | default('Accepter') }}" formnovalidate>
    </div>
{{ form_end(form) }}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Ça vous dit une nouvelle création' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1 class="text-center">Nouvelle création</h1>
            <p class="text-muted text-center">Ici vous pouvez publier uné création</p>
            {{ include('pins/_form.html.twig', {'submitButtonText': 'Créer'}) }}
        </div>
    </div>
{% endblock %}

templates/pins/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title pin.title ~ ' # Edition' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Edition # {{ pin.title }} #</h1>
            {{ include('pins/_form.html.twig', {'submitButtonText': 'Editer'}) }}
        </div>
    </div>
    
{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Vous avez ici toutes nos créations!' %}

{% block body %}

    <div class="p-5 mb-5 bg-light rounded-3">
      <div class="container-fluid py-5 text-center">
        <h1 class="display-1 fw-bold">{{ appName }}</h1>
        <p class="fs-4">Est l'endroit rêvé ou toutes vos créations prendront vies.</p>
        <a class="btn btn-primary btn-lg" type="button" href="#creation">Voir toutes nos créations</a>
      </div>
    </div>

    {% if pins|length > 0 %}
        {% for row in pins|batch(3) %}
            <div class="mb-5 row">
                    {% for pin in row %}
                        <div class="col-md-4 d-flex align-items-stretch">
                            <article class="pin bg-white rounded shadow" id="creation">
                                <div class="mw-100 overflow-hidden rounded-top">
                                     <a href="{{ path('app_pins_show', {slug: pin.slug}) }}">
                                        <img src="{{ (pin.imageName ? vich_uploader_asset(pin) 
                                            : asset('build/images/placeholder.jpg')) | imagine_filter('image_taille_moyenne') }}" 
                                            alt="{{ pin.title }}" class="w-100" 
                                        >
                                     </a>
                                </div>
                                <h2 class="h5 ps-3 pt-3">
                                    <a href="{{ path('app_pins_show', {slug: pin.slug}) }}" class="text-secondary text-decoration-none text-break">
                                        {{ pin.title }}
                                    </a>
                                </h2>
                                <p class="ps-3 pb-3 text-muted"><small>Publié par {{ pin.user.fullName }}</small></p>

                                <!--Code pour suprimer des créaions directement dans lindex--> 
                                <!--<a href="#" onclick="event.preventDefault(); confirm('Etes vous sûr?') &&
                                        document.getElementById('js-pin-form-delete-{{ pin.id }}').submit();" class="m-3 btn btn-danger">
                                        &times; Supprimer
                                </a>
                                <form id="js-pin-form-delete-{{ pin.id }}" action="{{ path('app_pins_delete', {slug: pin.slug}) }}" method="POST" style="display: none;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id)}}">
                                </form>-->

                            </article>
                         </div>
                    {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-5 h1 text-center">
            Aucun création n'a été publiée pour le moment 
            <a href="{{ path('app_pins_create') }}">Soyez le premier à en créer!</a>
        </p>
    {% endif %}

    <div class="mt-3 d-flex justify-content-center">
        {% do pins.setPageRange(2) %}
        {{ knp_pagination_render(pins, 'layouts/pagination.html.twig') }}
    </div> 
    
{% endblock %}

templates/pins/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title pin.title %}

{% block body %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<article class="pin bg-white rounded shadow">
				<div class="mw-100 overflow-hidden rounded-top">
					<img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/placeholder.jpg')) | imagine_filter('image_taille_moyenne') }}" alt="{{ pin.title }}" class="w-100">
				</div>
				<div class="p-3">
					<h1 class="h5 text-secondary text-break">
					    {{ pin.title | nl2br }}
					</h1>
					<p class="text-muted">
						<small>
							Publié <time datetime="{{ pin.createdAt|date('d-m-Y H:i:s')}}">{{ pin.createdAt|ago }}</time> par {{ pin.user.fullName }}
						</small>
					</p>
					<p class="pt-3 text-break">
						{{ pin.description | nl2br }}
					</p>
					{% if is_granted('PIN_MANAGE', pin) %}
						<div class="pt-3">
							<a href="{{ path('app_pins_edit', {slug: pin.slug}) }}" class="btn btn-outline-primary">Mettre à jour</a>
							<a href="#" onclick="event.preventDefault(); confirm('Etes vous sûr?') &&
									document.getElementById('js-pin-form-delete').submit();" class="btn btn-outline-primary">
									Supprimer
							</a>
							<form id="js-pin-form-delete" action="{{ path('app_pins_delete', {slug: pin.slug}) }}" method="POST" style="display: none;">
								<input type="hidden" name="_method" value="DELETE">
								<input type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id)}}">
							</form> 
						</div>
					{% endif %}
				</div>
			</article>
		</div>
	</div>
{% endblock %}